name: Publish Update

on:
  push:
    branches: ['*']

jobs:
  tsc-lint:
    steps:
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: TypeScript Check
        run: yarn tsc
      - name: Lint Check
        run: yarn lint

  publish-update:
    needs: tsc-lint
    steps:
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: Publish Update
        run: eas update --non-interactive